# 1.2.1 텐서 생성과 변환


In [1]:
import torch
import numpy

# 중첩 list를 지정
t = torch.tensor([[1, 2], [3, 4]])

# device를 지정하면 GPU에 텐서를 만들 수 있다.
t = torch.tensor([[1,2], [3, 4]], device = "cuda:0")

# dtype을 사용해 데이터형을 지정하여 텐서를 만들 수 있다
t = torch.tensor([[1,2], [3, 4]], dtype=torch.float64)

t = torch.arange(0, 10)

# 모든 값이 0인 100x10의 텐서를
# 작성해서 to메서드로 GPU에 전송

t = torch.zeros(100, 10).to("cuda:0")
t = torch.randn(100, 10)
print(t.size())

torch.Size([100, 10])


In [2]:
t = torch.tensor([[1, 2], [3, 4]])
x = t.numpy()

t = torch.tensor([[1, 2], [3, 4]], device = "cuda:0")
x = t.to("cpu").numpy()
print(x)
#텐서의 Numpy는 GPU상 텐서는 그대로 변환할 수 없고 CPU로 이동후에 변환해야 함

[[1 2]
 [3 4]]


# 1.2.2 텐서의 인덱스 조작

In [13]:
t = torch.tensor([[1, 2, 3], [4, 5, 6]])
t[0,2]
t[:,:2]
print(t)
t[:,[1,2]]
t[t>3]
t[0 ,1] = 100
t[:,1] = 200
t[t>10] = 20

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# Assuming that we are on a CUDA machine, this should print a CUDA device:

print(device)
print(t)

tensor([[1, 2, 3],
        [4, 5, 6]])
cuda:0
tensor([[ 1, 20,  3],
        [ 4, 20,  6]])


# 1.2.3 텐서연산
## 대규모 데이터를 처리할 때 GPU를 사용하기 때문에 조금 더 빠르게 처리 가능

In [16]:
# 길이가 3인 벡터
v = torch.tensor([1,2,3.])
w = torch.tensor([0,10,20.])
# 2x3의 행렬
m = torch.tensor([[0,1,2],[100,200,300]])
# 벡터와 스칼라의 덧셈
v2 = v + 10
print(v2)

tensor([11., 12., 13.])


In [18]:
# **의 경우 제곱을 의미
v2 = v**2
print(v2)

tensor([1., 4., 9.])


In [19]:
# 동일 길이 벡터 간 뺄셈
z = v-w
print(z)

tensor([  1.,  -8., -17.])


In [22]:
m3 = m + m
print(m3)

tensor([[  0,   2,   4],
        [200, 400, 600]])


In [28]:
# 5x5의 테스트 데이터 생성
x = torch.randn(5,5)
print(x)
# 수학 함수를 포함하는 수식
y = x*2 + torch.abs(x)
print(y)
# 평균치 구하기
m = torch.mean(x)
print(m)

m_value = m.item()
m2 = x.mean(0)
print(m2)

tensor([[-0.3505, -0.9197,  0.2431,  0.0525, -0.2246],
        [-0.0027, -0.1374, -1.7721,  0.1659, -0.2148],
        [-1.1342, -1.6556, -2.2396, -0.5513,  0.6070],
        [-1.3371,  0.1129, -1.9381,  0.6667,  0.6990],
        [-0.2455, -0.5073, -1.3586, -0.4287,  0.2208]])
tensor([[-0.3505, -0.9197,  0.7293,  0.1576, -0.2246],
        [-0.0027, -0.1374, -1.7721,  0.4976, -0.2148],
        [-1.1342, -1.6556, -2.2396, -0.5513,  1.8210],
        [-1.3371,  0.3388, -1.9381,  2.0002,  2.0971],
        [-0.2455, -0.5073, -1.3586, -0.4287,  0.6624]])
tensor(-0.4900)
tensor([-0.6140, -0.6214, -1.4131, -0.0190,  0.2175])


# 1.3 텐서와 자동 미분
## 텐서에는 requires_grad라는 속성이 있어서 True로 설정하면 자동 미분 기능 활성화 여기에 backward 메소드를 호출하면 그래프로부터 자동으로 미분 계산

In [30]:
x = torch.randn(100, 3)
a = torch.tensor([1,2,3.], requires_grad = True)

y = torch.mv(x,a)
o = y.sum()

o.backward()

a.grad != x.sum(0)

tensor([0, 0, 0], dtype=torch.uint8)